### ISSUE TITLE
KiCad missing files

### ISSUE THREAD

**Issue by peepo** [xesscorp/StickIt#1]
downloaded My First KiCad Board files and tried to open:
https://github.com/xesscorp/StickIt/blob/master/modules/OctalAdc/pcb/ADCXX8S.sch
in KiCad 0.201511251016+6329 on ubuntu 14.04

popup dialogue:
The following libraries were not found:
- C:/xesscorp/KiCad/libraries/xess
- special

searched for these files and this directory structure without success.
are some files missing?

Jonathan

**Comment by xesscorp** [comment]
I updated the project to remove these libraries and fix some errors that were induced when some of the schematic libraries were changed. Let me know if this fixes the problems.

**Comment by peepo** [comment]
I downloaded new zip file and tried to open StickIt.sch with eeschema,
selecting only option, Kicad schematic files (*.sch), popup dialogue:
StickIt-master/main/pcb/StickIt.sch' is NOT an Eeschema file!

i tried opening StickIt.brd with Pcbnew,
selecting file type Kicad PCB files (*.brd),
however, the dialogue 'hangs'
ie I can press the open button repeatedly,
but the dialogue does not close or change, and there is no content displayed.

**Comment by xesscorp** [comment]
On 12/02/2015 6:12 PM, Jonathan Chetwynd wrote:

> I downloaded new zip file and tried to open StickIt.sch with eeschema,
> selecting only option, Kicad schematic files (*.sch), popup dialogue:
> StickIt-master/main/pcb/StickIt.sch' is NOT an Eeschema file!

That isn't a KiCad schematic. It's an Eagle schematic made back when I 
was using that CAD package. The only KiCad project in the StickIt repo 
is the OctalAdc folder. (BTW, I fixed the OctalAdc design so it might 
work for you now.)

> i tried opening StickIt.brd with Pcbnew,
> selecting file type Kicad PCB files (*.brd),

No, KiCad PCB files have the .kicad_pcb suffix. Eagle PCB files have the 
.brd suffix.

> however, the dialogue 'hangs'
> ie I can press the open button repeatedly,
> but the dialogue does not close or change, and there is no content 
> displayed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/StickIt/issues/1#issuecomment-161463438.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by peepo** [comment]
Oops! apologies, it was 11:00 at night after a long day...

seems ready to use, however,
I opened .pro with kicad, using GUI:
launched eeschema open .sch, looks okay.
launched pcbnew looks good, but get dialogue:

The following libraries were not found:
ADCXX8S-rescue

now have to find time...

~:"

**Comment by xesscorp** [comment]
Hmm. I just downloaded the entire repo and opened the OctalAdc project in KiCad without a problem. I did notice that the ADCXX8S-rescue library is still in the list of component libraries of Eeschema (Preferences => Component Libraries). You can remove that library (it isn't needed) and maybe that dialog will disappear.
